### ISSUE TITLE
cast转换异常

### ISSUE THREAD

**Issue by h-zhouwenjun** [jeasonlzy0216/PullZoomView#10]
java.lang.ClassCastException: com.rablive.jwrablive.a.a.a cannot be cast to java.lang.String
	at com.lzy.widget.PullZoomView.a(PullZoomView.java:130)
	at com.lzy.widget.PullZoomView.a(PullZoomView.java:137)
	at com.lzy.widget.PullZoomView.a(PullZoomView.java:137)
	at com.lzy.widget.PullZoomView.a(PullZoomView.java:137)
	at com.lzy.widget.PullZoomView.a(PullZoomView.java:137)
	at com.lzy.widget.PullZoomView.a(PullZoomView.java:137)
	at com.lzy.widget.PullZoomView.a(PullZoomView.java:137)

**Comment by jeasonlzy** [comment]
pullzoomview 需要的tag是固定的格式，可能你使用了想 glide 这些会对tag进行修改的项目，所以就异常了。。

**Comment by h-zhouwenjun** [comment]
zoom对象View包含ImageView，ImageView使用的Glide加载的图片。这种情况会导致tag报错吗？请问怎么可以解决

**Comment by jeasonlzy** [comment]
这个会导致的。。因为glide使用了tag，他会修改tag，导致异常，最好的方法就是把tag写成自定义属性，这个可以自己修改一下。
