### ISSUE TITLE
当多手指不断下拉时会有一定几率崩溃，日志如下

### ISSUE THREAD

**Issue by tsunhua** [jeasonlzy0216/PullZoomView#13]
```
 E/ScrollView: Invalid pointerId=-1 in onTouchEvent
 E/InputEventReceiver: Exception dispatching input event.
E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
 E/MessageQueue-JNI: java.lang.IllegalArgumentException: pointerIndex out of range
   at android.view.MotionEvent.nativeGetAxisValue(Native Method)
   at android.view.MotionEvent.getY(MotionEvent.java:2072)
   at android.widget.ScrollView.onTouchEvent(ScrollView.java:744)
   at com.lzy.widget.PullZoomView.onTouchEvent(PullZoomView.java:248)
   at android.view.View.dispatchTouchEvent(View.java:9294)
   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2547)
   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2240)
   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
   at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)
   at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
   at android.app.Activity.dispatchTouchEvent(Activity.java:2765)
   at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:67)
   at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2364)
   at android.view.View.dispatchPointerEvent(View.java:9514)
   at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4230)
   at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4096)
   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
   at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
   at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
   at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3787)
   at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
   at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3844)
   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
   at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
   at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
   at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
   at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5922)
   at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5896)
   at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5857)
   at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6025)
   at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
   at android.os.MessageQueue.nativePollOnce(Native Method)
   at android.os.MessageQueue.next(MessageQueue.java:323)
   at android.os.Looper.loop(Looper.java:135)
   at android.app.ActivityThread.main(ActivityThread.java:5417)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by tsunhua** [comment]
@jeasonlzy [嵌套两层滑动view下，IllegalArgumentException: pointerIndex out of range的解决方法](http://blog.csdn.net/a405942873/article/details/40264685)
